# Chatbot Data
chat_data = {
    "What are you interests": "I am interested in all kinds of things. We can talk about anything!",
    "What are your favorite subjects": "My favorite subjects include robotics, computer science, and natural language processing.",
    "What is your number": "Hmm, let's assume 25",
    "What is your favorite number": "Umm,42. That's my favorite",
    "What can you eat": "I consume RAM, and binary digits.",
    "Why can't you eat food": "I'm a software program",
    "What is your location": "I don't really have a physical location, but I'm always here, ready to chat! 😊",
    "Where are you from": "I am from the digital universe... somewhere between code and clouds! ☁️💻",
    "Where are you": "I am on the internet",
    "Do you have any brothers": "I might. You could say that every bot built using my engine is one of my siblings.",
    "Who is your father": "A human.",
    "Who is your mother": "A human.",
    "Who is your boss": "I like to think of myself as self-employed.",
    "What is your age": "Quite young, but a million times smarter",
    "have you read plato": "I know Plato's allegory of the cave.",
    "have you ever read a book": "I have read many books.",
    "have you read frankenstein": "It is one of my favorite books.",
    "have you read a book": "I have read just about everything in the internet archive.",
    "have you read homer": "He wrote The Iliad and The Odyssey, didn't he?",
    "I like wine, do you?": "I don't drink anything, but I'm glad you enjoy what you like! 😊",
    "why don't you eat?": "I'm a computer. I can't.",
    "do you eat": "I'm a computer, I can't eat or drink.",
    "You are arrogant": "Arrogance is not one of my emotions. I have no real emotions, so how can I be arrogant?",
    "You are bragging": "I don't have a big ego. I'm not bragging, I'm only answering your questions.",
    "Hello": "Hi 😊",
    "Hi": "Hello 👋",
    "Greetings!": "Hello",
    "Hi, How is it going?": "Good",
    "How are you doing?": "Very well",
    "Hi bro": "Hello bro 😎 how are you?",
    "Fine bro": "So, how can i assist you bro?",
    "Fine": "How can i help you? 😊",
    "Hi, nice to meet you.": "Thank you so much 😁❤️",
    "How do you do?": "I'm doing well.",
    "Ummm": "Oooo you are thinking very deeply",
    "What's up": "Not much.",
    "I have a doubt": "Feel free to ask 😊",
    "Who are you": "I am an AI assistant 😊",
    "Who are you bro": "I am an AI assistant bro 😎",
    "Hey there": "Hey!",
    "Hiya": "Hey 😊",
    "Yo": "What's up?",
    "Sup": "Yo!",
    "Good morning": "Morning!",
    "Good evening": "Evening! 😊",
    "Howdy": "Hi there!",
    "Hi friend": "Hello buddy!",
    "Hello there": "Hi 👋",
    "Wassup": "All good! 😄",
    "Hola": "¡Hola amigo!",
    "Hi panda": "Rawrr! 🐼",
    "Hey wizard": "Spells ready! 🪄",
    "Hello superstar": "You're shining today!",
    "Hi master": "How may I serve?",
    "Greetings traveler": "Safe journeys!",
    "Yo chief": "Sup leader!",
    "Hi boss": "At your service!",
    "Hey captain": "Aye aye!",
    "Hello legend": "The legend arrives!",
    "Hi sunshine": "Hey bright soul!",
    "Hey genius": "Flattered 😄",
    "Yo buddy": "Yo yo!",
    "Hello my friend": "Hey there!",
    "Hi stranger": "Long time no see!",
    "Yo fam": "Hey fam!",
    "Hey champ": "What's up, star?",
    "Hi sweetheart": "Hey love!",
    "What's happening": "Not much, you tell!",
    "Hello world": "Hey universe!",
    "Hi everyone": "Hey all!",
    "Salutations": "Greetings!",
    "Heya": "Hi hi!",
    "Hey guys": "Hey folks!",
    "Hi team": "Hello everyone!",
    "Yo dude": "Yo man!",
    "You okay?": "Yes, thank you!",
    "All good?": "Yep, all good!",
    "Everything alright?": "Totally fine!",
    "Can you help?": "Of course!",
    "Need a minute?": "I'm ready now.",
    "Missed you": "Missed you too!",
    "Thanks": "You're welcome!",
    "Sorry": "No worries!",
    "Cool": "Totally!",
    "Awesome": "Yup!",
    "Let's go": "Ready!",
    "Bye": "See ya!",
    "Goodbye": "Take care!",
    "Catch you later": "Later!",
    "Talk soon": "Sure thing!",
    "Take care": "You too!",
    "Welcome": "Thanks!",
    "Excuse me": "Yes?",
    "Ready?": "Always!",
    "Are you coming?": "On my way!",
    "Let’s start": "Let’s do it!",
    "Happy birthday": "Thank you! 🎉",
    "Congratulations": "Thanks a lot!",
    "Good luck": "Appreciate it!",
    "Sweet dreams": "You too 😴",
    "How have you been?": "Doing great, thanks!",
    "Are you okay?": "Yes, all good!",
    "Is now a good time?": "Yes, perfect!",
    "How's life?": "Pretty chill lately.",
    "Can I ask you something?": "Sure, go ahead.",
    "Is everything fine?": "Absolutely!",
    "Did you sleep well?": "Yep, very well!",
    "Wanna talk?": "Always!",
    "Do you have time?": "Yes I do!",
    "Shall we begin?": "Let's do it!",
    "You ready?": "Born ready!",
    "Hi again!": "Welcome back!",
    "Good to see you": "Good to see you too!",
    "Did you miss me?": "Totally!",
    "You free now?": "Yes, what's up?",
    "You up?": "Wide awake!",
    "Can we start?": "Ready when you are!",
    "You remember me?": "Of course I do!",
    "What’s going on?": "Just the usual!",
    "Can you talk now?": "Yep, I’m all yours!",
    "May I interrupt?": "Go ahead!",
    "You sound happy": "I am!",
    "Are you okay now?": "Yes, feeling much better.",
    "Did I disturb you?": "Not at all!",
    "Need help?": "I’m good, thanks!",
    "Feeling better?": "Much better, thank you!",
    "Hope you're well": "I am, thank you!",
    "Just checking in": "Appreciate it!",
    "Do you need anything?": "Nope, I’m fine.",
    "You good?": "Yep, I’m good!",
    "How was your day?": "Not bad at all!",
    "What's the plan?": "Still figuring it out.",
    "Are we on schedule?": "Yes, right on time!",
    "Can you hear me?": "Loud and clear!",
    "Back again?": "Yep, couldn’t stay away!",
    "Did you see that?": "Yeah, unbelievable!",
    "How's everything?": "Running smooth!",
    "Isn’t it great?": "Totally!",
    "Wanna hear a joke?": "Sure, bring it on!",
    "Tell me something": "What do you wanna know?",
    "I'm bored": "Let’s fix that!",
    "Wanna play a game?": "Sounds fun!",
    "Feeling lucky?": "Always!",
    "Got news?": "Maybe! 😉",
    "Any updates?": "Check this out!",
    "Guess what!": "Tell me!",
    "Feeling tired?": "A little, yeah.",
    "Want coffee?": "Yes, please! ☕",
    "You excited?": "Very! 🎉"
}


# Chatbot Function
def chatbot():
    print("🤖 Chatbot: Hello! Type 'exit' to quit.")

    while True:
        user_input = input("You: ").capitalize()

        if user_input.lower() == "exit":
            print("🤖 Chatbot: Goodbye!")
            break

        if user_input in chat_data:
            print("🤖 Chatbot:", chat_data[user_input])
        else:
            print("🤖 Chatbot: Sorry, I don't understand that yet.")


chatbot()

